### ISSUE TITLE
Migrate to Lucene 6.3.0?

### ISSUE THREAD

**Issue by Peilin-Yang** [lintool/Anserini#111]
I have created a PR for migrating the Lucene to the latest version 6.3.0
The current version we use is 5.3.0 and we've used this version for over 1 year.
I think it is better to keep the pace with the Lucene main trunk so the users/developers of Anserini can easily find the documentations, StackOverflow discussions, etc.

Thoughts?

**Comment by lintool** [comment]
Completed as part of #110
