### ISSUE TITLE
add eval module?

### ISSUE THREAD

**Issue by Peilin-Yang** [lintool/Anserini#119]
@lintool 
I have a local branch which adds the `eval` module to the repo.
The advantage is obvious:
- the project is more independent to `trec_eval` and `gdeval.pl`
- we can add `-eval` option to `SearchCollection` and get effectiveness automatically generated.

But I want to first make sure that you also favor the changes.
If you are interested I will create the PR.

**Comment by lintool** [comment]
I think this is a good idea, but does your code generate *exactly* the same results as the traditional eval scripts, including tie-breaking behavior, etc.?

**Comment by lintool** [comment]
Merged as part of https://github.com/lintool/Anserini/pull/120
