### ISSUE TITLE
API to fetch raw document text

### ISSUE THREAD

**Issue by lintool** [lintool/Anserini#122]
Given a raw document id, I want to fetch the actual document text. This should be a method as part of the collection class, something like `Collection.getRawDocument(String docid)`:
https://github.com/lintool/Anserini/blob/master/src/main/java/io/anserini/collection/Collection.java

To implement this, we'll need to store the following information: docid, file, offset, length.

Since for large collections this will be rather large, we should store this itself in a Lucene index. So this means we need a helper program to build this Lucene index.

**Comment by minafarid** [comment]
This is a piece of code that I write before to retrieve a specific document given its id. Might help.

```java
public String getDocumentById(String docId) throws Exception {
        GetResponse response = client.prepareGet(indexName, docType, docId).execute().actionGet();
        if (response == null)
            return null;

        Map<String, Object> source = response.getSource();
        if (source == null)
            return null;

        Object content = source.get(contentFieldName);
        return content.toString();
    }

```

**Comment by minafarid** [comment]
This is some function that I used before to retrieve a document given its ID. The index was built using Anserini.
```java
public String getDocumentById(String docId) throws Exception {
        TermQuery query = new TermQuery(new Term(FIELD_ID, docId));
        TopDocs results = searcher.search(query, 5);
        for (ScoreDoc scoreDoc : results.scoreDocs) {
            int docIndex = scoreDoc.doc;
            String docText = indexReader.document(docIndex).get(FIELD_BODY);
            return docText;
        }
        return null;
    }
```

**Comment by lintool** [comment]
This means in the indexer you are storing the raw document text, right? This bloats the index... and won't be scalable if we want to access all of ClueWeb09 or ClueWeb12.

**Comment by minafarid** [comment]
Yes, I was storing the document body as well.

**Comment by Peilin-Yang** [comment]
This is what I have.
https://github.com/lintool/Anserini/blob/master/src/main/java/io/anserini/index/DumpIndex.java#L141-L151

**Comment by lintool** [comment]
@minafarid @Peilin-Yang Yes, I don't want to store the raw doc in the index... way too much bloat... ultimately we want access to all ~700 million docs in ClueWeb12, right?

Only practical approach is to go back and fetch the doc from raw WARCs?

**Comment by lintool** [comment]
@Peilin-Yang in your code, where do you decided whether or not to store the raw doc? I don't see an option in `IndexArgs`?

**Comment by Peilin-Yang** [comment]
@lintool you're right. It needs the `store_raw_doc` option.

**Comment by lintool** [comment]
So, here's the question - should we have a `store_raw_doc` option, so for smaller collections we just stuff into the Lucene index directly? Or should we say, we'll always read from raw collection?

**Comment by Peilin-Yang** [comment]
Yes, this is interesting...I did not think this too much for the super large collection like CW12.
And I think you're correct - we need the file, offset and length in the index.
But if we detach the raw collection from the index then we have the risk that the raw collection (for some reason) is no longer available. Right?

**Comment by lintool** [comment]
All of ClueWeb12 is 5.54 TB... seems a bit burdensome, no?

**Comment by lintool** [comment]
Well, I've decided we shouldn't guess... let's actually run some experiments to find out the answer. See #126

**Comment by lintool** [comment]
We've implemented the functionality as part of `IndexUtils`. Experiment results in #126. Closing issue.
