### ISSUE TITLE
Play with storing documents directly in the index

### ISSUE THREAD

**Issue by lintool** [lintool/Anserini#126]
Experiment with storing documents directly in the index to see how much extra space it takes...

**Comment by lintool** [comment]
I implemented an indexing option to the text directly in the corpus. Here are some experimental results on gov2:

```
 81G original gov2 collection
 11G index, cnt 
 37G index, positions
 82G index, positions + docvectors
150G index, positions + docvectors + doc text
```

Note that this is storing the cleaned doc text (Jsoup removal of HTML pages, etc.). If we wanted to store the raw text, that would be even *more* space.

**Comment by minafarid** [comment]
It looks like the difference between the `82G` and the `150G` is aprpox. the original `81G` documents size, which makes sense since we are storing the original text again in the index.

To me, the size of the index doesn't matter that much. Performance of querying and retrieving documents is more important. If the query performance is hurt, then it is better not to store the document text in the index.

The benefits of storing document text together with the index (as I see it, **please feel free to correct me or add more**) are:

1. Makes the index portable and decoupled from the original data. I just copy the index directory to a new machine, and I have all documents with it.
2. When querying, it saves some time to retrieve the document text in the query results than fetching documents separately

**Comment by lintool** [comment]
I will verify if storing the documents hurts query retrieval performance. I do not think so because IIRC, Lucene fields are stored in "columnar" format.

I will also add an option to store the *raw* document and see how that changes the size. The difference is things like HTML cleaning. Of course, we can always reclean the raw document on demand.

@minafarid Correct, storing the doc makes the index completely portable.

Here's my current thinking: for ClueWeb09b and ClueWeb12-B13, we can probably store the docs. Guesstimate, the entire index will be ~0.5 TB, which is not *that* bad. However, I really can't justify the same for ClueWeb12. That's 5TB of text alone, so estimated index w/ everything will be 10TB. Each.

**Comment by lintool** [comment]
`-storedocs` option merged in as PR #130 
Leaving issue open for further discussion.

**Comment by lintool** [comment]
Okay, here's the update:

```
 81G original gov2 collection
 11G index, cnt 
 37G index, positions
 82G index, positions + docvectors
150G index, positions + docvectors + doc text
219G index. positions + docvectors + raw docs
```

The 81G raw collection becomes 137G once you stuff it into Lucene... I think the size increases because the compression isn't as efficient.

Thoughts?

**Comment by msci342prof** [comment]
One idea: Often significant compression is obtained by how documents are
ordered in the stream.  If each doc is separately compressed, you will lose
that advantage.

Mark

**Comment by lintool** [comment]
The question is: is it worth blowing a TB (let's say) for ClueWeb09b or ClueWeb12-B13? Our new machine has 84T disk. If we all share a common index (for each), that's totally fine and worth it. But if everyone starts playing with variants (different stemming, stop/nostop, etc.), then things are going to get out of hand very quickly. So this is as much a policy issue of how we as a group want to operate...

**Comment by lintool** [comment]
Here are some results of index size and indexing time on our new machine, tuna. Here, I'm using 88 threads for indexing, but I suspect that's overkill, since beyond a certain point you run into diminishing returns from more parallelism.

ClueWeb09

```
231G ClueWeb09b collection size

 27G 01:00:34 lucene-index.cw09b.cnt
 73G 01:52:20 lucene-index.cw09b.pos
176G 02:15:12 lucene-index.cw09b.pos+docvectors
323G 03:06:06 lucene-index.cw09b.pos+docvectors+docs
688G 04:29:31 lucene-index.cw09b.pos+docvectors+rawdocs
```

ClueWeb12-B13

```
383G ClueWeb12-B13 collection size

 27G 01:08:33 lucene-index.cw12b13.cnt
 74G 02:01:50 lucene-index.cw12b13.pos
173G 02:35:56 lucene-index.cw12b13.pos+docvectors
310G 03:29:51 lucene-index.cw12b13.pos+docvectors+docs
867G 06:01:02 lucene-index.cw12b13.pos+docvectors+rawdocs
```

**Comment by lintool** [comment]
Code that stores documents has been in use for a while and appears to be stable. Closing.
