### ISSUE TITLE
Refactor Twitter NRTS package to use a templating system

### ISSUE THREAD

**Issue by lintool** [lintool/Anserini#14]
For the Twitter NRTS demo, we should probably use a proper templating system like mustache to avoid `System.out.println` nightmare: https://github.com/spullara/mustache.java

**Comment by xeniaqian94** [comment]
commit 3114eaad6e521ebfcd70f5e7c07416c630abcb52, tentatively request to merge into Luchen's 1-commit ahead branch.

**Comment by lintool** [comment]
Fixed commit 5609337de7656662b590f32e6fbbdb4c45689ac5
