### ISSUE TITLE
QA system: vary top k documents in retrieval stage

### ISSUE THREAD

**Issue by lintool** [lintool/Anserini#153]
We should have an option to vary the top *k* documents that are analyzed, i.e., tokenized into sentences and scored as passages.

@rosequ or @salman1993 ?

**Comment by rosequ** [comment]
@lintool this is already a part of the `RetrieveSentences.java` and can be specified with `-hits` option.

**Comment by salman1993** [comment]
I think this topic is closed. We can now specify the 'k' parameter from the front-end and get top k results back.

**Comment by rosequ** [comment]
@salman1993 this is at the retrieval stage and not at the front-end, no?

**Comment by salman1993** [comment]
getRankedPassages(String query, int numHits, int k) in the PyseriniEntryPoint class returns a list of the top 'k' ranked passages and the client app shows those results.

**Comment by rosequ** [comment]
Yes, that's what I meant... We have a method to retrieve and analyze :)
