### ISSUE TITLE
Indentation size

### ISSUE THREAD

**Issue by lintool** [lintool/Anserini#16]
@iorixxx Do you mind if we agree on code indentation being two spaces, just to be consistent?

If so, can you please reformat your code? I'd rather you do it so better retain history for `git blame`. Please send pull request.

Thanks!

**Comment by lintool** [comment]
Merged 09e4fa5ece0c3d398d86306a50e7033ec26b7eac

**Comment by iorixxx** [comment]
Ups commons cli dependency (that I removed) was still used, didn't know that.
