### ISSUE TITLE
Indexing all of ClueWeb09

### ISSUE THREAD

**Issue by lintool** [lintool/Anserini#18]
Quite impressively, I was able to index all of ClueWeb09 (English):

```
nohup sh target/appassembler/bin/IndexClueWeb09b \
  -input /scratch1/collections/ClueWeb09.English/data/ \
  -index lucene-index.cw09.cnt -threads 32 -optimize >& log.cw09.cnt.txt &
```

Took ~18 hours:

```
2015-10-16 07:51:04,775 INFO  [main] index.IndexClueWeb09b (IndexClueWeb09b.java:298) - Total 503781465 documents indexed in 18:01:04
```

Index size (note: no positions):

```
$ du -h lucene-index.cw09.cnt/
254G    lucene-index.cw09.cnt/
```

**Comment by iorixxx** [comment]
I was able to index whole CW09 dataset, with slight modifications to IndexClueWeb09b class. With 15 threads and 50gb to heap, it took about 20 hours and ended up in index size of 650 GB.
