### ISSUE TITLE
IndexCounter code broken

### ISSUE THREAD

**Issue by lintool** [lintool/Anserini#28]
@LuchenTan IndexCounter code doesn't compile, so `master` is currently broken right now.

+ Wrong package
+ Uses `Args` class which has been removed. See `IndexGov2` for example of how to use args4j
+ Class has a weird name - can you please rename to `DumpDocids` or something like that?
+ Can you please change indentation to 2 spaces instead of tab. Search online for Eclipse code formatter, one of the options is indentation - change to make consistent with everyone else.

**Comment by LuchenTan** [comment]
I've fixed the code. And send a new pull request.

**Comment by lintool** [comment]
Code review on pull request. Please address.

**Comment by lintool** [comment]
Fixed commit 5609337de7656662b590f32e6fbbdb4c45689ac5
