### ISSUE TITLE
Embed tweets for presentation in search results in NRTS demo

### ISSUE THREAD

**Issue by lintool** [lintool/Anserini#33]
@xeniaqian94 take a look at this:
https://dev.twitter.com/web/embedded-tweets

In the NRTS demo search results, let's embed tweets for presentation. Check out this as an example:
http://lintool.github.io/JScene/search-demo.html

**Comment by xeniaqian94** [comment]
Will fix it soon. 

A small puzzle is to correctly render css/js element into a Mustache template, in specific, putting files like <code>bootstrap.min.css</code> in the correct directory when referred in template <pre><code> \<link href="bootstrap.min.css" rel="stylesheet"></code></pre> Inline css/js codes could work but separate js/css file would be preferable for good organization.

Posted the question Mustache community, waiting for some help...
https://github.com/spullara/mustache.java/issues/159

**Comment by lintool** [comment]
You can just link to a publicly available absolute URL?

**Comment by aroegies** [comment]
This isn't (necessarily) a Mustache issue. 

It has to do with how Jetty is being configured to serve up static files. Currently it isn't.

The simplest solution is to do as Jimmy suggested and use a CDN for the necessary bits.

The "better" solution would be to correctly configure the Jetty server to serve static content. In doing so, we have the ability to develop more interesting web applications later. 

I'm not super familiar with Jetty but I believe the two easiest options are:
- edit the doGet function in TweetServlet and manually serve up the necessary files
  + This is the super hacky way to do it and you probably don't want this
- actually set up a static content directory and serve from there
   + See http://stackoverflow.com/questions/10284584/serving-static-files-w-embedded-jetty
   + The Jetty tutorial also talks about this a bit (apparently)
   + The real trick here is to set up static content serving and dynamic content to work well together.    In node.js, this means getting the order of setting handlers right. Likely means something similar here but with more Java cruft.

**Comment by lintool** [comment]
Agree with @aroegies
Yes, serving static content is something we'll need to eventually do.

**Comment by aroegies** [comment]
So as it turns out, I didn't want to do any actual work today and got this entire thing working.

That is:
- serving up static content
- embedding tweets with the Twitter Embed API

There are pretty-ification issues with the current displaying of embeded tweets but that's neither here nor there. 

In addition, there is probably a better way to use Mustache to doing the tweet embedding but the way I did was the most expedient and didn't involve me learning too much about Mustache.

See commit a37b5079557024e767356bd55f939519274eadf5 in my fork for code.

**Comment by xeniaqian94** [comment]
Thanks for the help/code. Then let me follow up with the rest trivial part.

**Comment by lintool** [comment]
@xeniaqian94 seems like @aroegies fixed this: https://github.com/aroegies/Anserini/commit/a37b5079557024e767356bd55f939519274eadf5

Look at that branch? See https://github.com/lintool/Anserini/network for context.

**Comment by lintool** [comment]
Merged commit 35690612eead265e7b7284ab13cfee0b8de5f4f3
