### ISSUE TITLE
LTR data generator needs access to qrels

### ISSUE THREAD

**Issue by lintool** [lintool/Anserini#47]
@claclark The feature data that the LTR module generates needs to have access to the qrels so the relevance grade can be folded directly into the output.

**Comment by lintool** [comment]
Fixed. commit 030fe0e4d845a48409fe7c065ad17ceedec95de9

**Comment by claclark** [comment]
By hard-coding the name of the qrel file?  Shouldn't this type of resource live in the Lucene index directory under a standard name.

**Comment by lintool** [comment]
Re-opening issue since Charlie noted bug.

**Comment by lintool** [comment]
Fixed (again) commit f23faddd40b0e5919b4b8b764da8b10c6e86b8e2
