### ISSUE TITLE
Code Comments

### ISSUE THREAD

**Issue by aroegies** [lintool/Anserini#52]
Before we get too far into hacking on Anserini, we should probably decide on how we want to deal with comments.

Do we want to do Javadoc? Something else?

**Comment by claclark** [comment]
If it was hard to write it should be hard to read?

**Comment by lintool** [comment]
Simple solution: write self-documenting code :)

Java is so braindead and verbose that this isn't so difficult.

Javadoc for API documentation:

```
/** foo 
*/
```

Everything else can be inline:

```
// Here is an explanation of some complex algorithm.
```
