### ISSUE TITLE
Consider using ThreadPoolExecutor in Gov2 indexer

### ISSUE THREAD

**Issue by iorixxx** [lintool/Anserini#54]
Instead of calling/invoking [thread.start()](https://github.com/lintool/Anserini/blob/master/src/main/java/io/anserini/index/Gov2IndexThreads.java#L60) manually, we can switch to [ThreadPoolExecutor](http://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ThreadPoolExecutor.html), which usually provides improved performance when executing large numbers of asynchronous tasks.

**Comment by iorixxx** [comment]
Gov2 indexer: Total 25172934 documents indexed in 00:59:28 
emptydocids.txt 32245

**Comment by iorixxx** [comment]
indexed documents plus document that are empty sum up to the number (25,205,179
documents) reported at official site : http://ir.dcs.gla.ac.uk/test_collections/gov2-summary.htm
25172934 + 32245 = 25205179

**Comment by lintool** [comment]
What are the specs of your machine? I.e., exact processor model? For example our main machine "streeling" is:

+ 2 x Intel Xeon E5-2680 v3 2.5GHz (12 cores)
+ 768 GB RAM

Detailed specs would help compare performance.

**Comment by iorixxx** [comment]
`less /proc/cpuinfo` says Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz
processor number goes upto 39. It has 128 GB RAM.
However, I use `java -server -Xms20g -Xmx20g` and 15 threads.

**Comment by lintool** [comment]
The intel spec here is here: [E5-2650 v3 @ 2.30GHz](http://ark.intel.com/products/81705/Intel-Xeon-Processor-E5-2650-v3-25M-Cache-2_30-GHz). Main difference is that we have 12 cores to your 10 (and hence more cache); and also higher clock freq. But the hardware is quite similar.

**Comment by lintool** [comment]
Merged to master https://github.com/lintool/Anserini/commit/cfb10c97c904423ca1c460f768a5bd3edf1b3d12
