### ISSUE TITLE
Lucene query parser cannot parse wildcard queries

### ISSUE THREAD

**Issue by rosequ** [lintool/Anserini#61]
Lucene query parser gives the following error if the query has wildcard characters in it:
_'*' or '?' not allowed as first character in WildcardQuery_
Ex: Cannot parse 'where is the Eldorado Casino in Reno ?': '*' or '?' not allowed as first character in WildcardQuery.

**Comment by iorixxx** [comment]
There are two options here:

* Escape the characters that are part of the query syntax using queryparser.classic.QueryParserBase#escape

* Tokenize the query string and create the Lucene Query object by your self without a query parser.
