### ISSUE TITLE
Nondeterminism in documents indexed for Gov2?

### ISSUE THREAD

**Issue by lintool** [lintool/Anserini#7]
Indexing Gov2 on streeling at UMD, I get 24899563 docs.
Luchen reports 24900602 docs indexing on hops.

Weird - some non-determinism the multi-threading?

Not that important if we can replicate effective results on standard test collections, but worth noting.

**Comment by LuchenTan** [comment]
I redo the Gov2 indexing on Hops at UWaterloo, and the same number of documents, 24900602 docs indexed.

**Comment by claclark** [comment]
1000 documents don't appear from nowhere

**Comment by lintool** [comment]
As Charlie suggested in email (and the sensical thing to do), we should dump out the docids and diff.

@LuchenTan so you can start learning the Lucene APIs, etc., can you write a simple program that does this?

Fork the repo, add in your code, and send a pull request. The ultimate product should be a command I can copy and paste to generate the output (documented in the README).

Thanks!

**Comment by LuchenTan** [comment]
OK, I'll do it.

**Comment by lintool** [comment]
Update on this: as is turned out, there was a minor corruption in the copy of Gov2 at UMD. After fixing this and rerunning the indexer, I get 24900602 docs, which machines @LuchenTan's number.

**Comment by LuchenTan** [comment]
Yes, exactly the same number of mine.

On Thu, Oct 15, 2015 at 2:02 PM, Jimmy Lin <notifications@github.com> wrote:

> Update on this: as is turned out, there was a minor corruption in the copy
> of Gov2 at UMD. After fixing this and rerunning the indexer, I get 24900602
> docs, which machines @LuchenTan <https://github.com/LuchenTan>'s number.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lintool/Anserini/issues/7#issuecomment-148474012>.
>



-- 
Luchen Tan

David R. Cheriton School of Computer Science
University of Waterloo
Waterloo, Ontario, Canada N2L 3G1

**Comment by lintool** [comment]
Resolving issue... basically, no issue.

**Comment by lintool** [comment]
Merged in Luchen code to dump out docids in an index:
commit 491dd9e18a562591f7d43feaf0706c21b3235952
