### ISSUE TITLE
Earlier TRECs baseline results

### ISSUE THREAD

**Issue by Peilin-Yang** [lintool/Anserini#79]
add qrys and qrels to the resources and (possibly?) add parsing topics file.

**Comment by lintool** [comment]
Yes, we should check in the topics and qrels from old TREC collections. These should go in `src/main/resources/topics-and-qrels/` - please follow the same naming convention?

**Comment by Peilin-Yang** [comment]
Yes, I saw the resources and will follow the same convention.

**Comment by Peilin-Yang** [comment]
merged
