### ISSUE TITLE
Reorganize docs

### ISSUE THREAD

**Issue by lintool** [lintool/Anserini#85]
I don't like GitHub's wiki feature because it's hard to give fine-grained write permission to people.

How about we just move `*.md` into a `docs/` folder and check them into the repo directly? The top-level README can just point to `foo.md` in the `docs/` folder?

That way we keep docs + code in the same repo, preserving history, etc.

Thoughts?

**Comment by Peilin-Yang** [comment]
`docs/*.md` can solve the problem of write permission.
Maybe an up-to-date Wiki is more user friendly?
Is it easy to make linkages between `*.md`?

**Comment by lintool** [comment]
@Peilin-Yang Yes, we can add links using relative paths. So this isn't any different from Wiki, especially since GitHub gives you in-place md updates now.

Check out: https://github.com/lintool/Anserini/tree/reorganize-docs

**Comment by Peilin-Yang** [comment]
@lintool this is much better now!

**Comment by lintool** [comment]
Okay, I will shipit then.
