### ISSUE TITLE
Add nDCG to ClueWeb results

### ISSUE THREAD

**Issue by Peilin-Yang** [lintool/Anserini#92]
just use `trec_eval -m ndcg_cut.20` would do the trick

**Comment by lintool** [comment]
Interesting. The above command and `gdeval` at https://github.com/trec-web/trec-web-2013/blob/master/src/eval/gdeval.pl seem to give different values. The TREC overview papers seems to match the `gdeval` numbers. Wonder what's going on?

**Comment by Peilin-Yang** [comment]
I think `gdeval.pl` should be favored.
`trec_eval` uses `gain/log2(i)` to compute dcg/idcg while `gdeval` uses `(2^gain-1)/log2(i+1)`
The latter is widely adopted by industry (see https://en.wikipedia.org/wiki/Discounted_cumulative_gain and https://www.kaggle.com/wiki/NormalizedDiscountedCumulativeGain).
Maybe we can include `gdeval.pl` to the repo?

**Comment by lintool** [comment]
Done, as part of #113
