### ISSUE TITLE
Refactoring of indexing API (again)

### ISSUE THREAD

**Issue by lintool** [lintool/Anserini#95]
Currently, we have the notion of `SourceDocument`, and a `Collection` provides an iterator over `SourceDocument`s. Now, Lucene requires its own document class `Document` as an input to the indexer.

So, here's a proposed API: we build a `LuceneDocumentGenerator<D extends SourceDocument>`, and we can use Guava iterator transformations to convert `Iterator<SourceDocument>` to `Iterator<Document>`, which we can directly pass to the indexer. Seems like a pretty clean API.

Thoughts?

**Comment by Peilin-Yang** [comment]
Basically this is the refactor of https://github.com/lintool/Anserini/blob/master/src/main/java/io/anserini/index/IndexThreads.java#L72-L140 ?

**Comment by lintool** [comment]
Correct - the idea is to generalize and abstract out that block of code.

**Comment by Peilin-Yang** [comment]
Do you already have a branch for this?

**Comment by lintool** [comment]
Work in progress on branch `index-refactoring`.

**Comment by lintool** [comment]
@Peilin-Yang I have created pull request #100 for this. Let me know what you think?
I realize all the documentation needs to be updated - I will circle around and do that once I verify all the collections work.

**Comment by Peilin-Yang** [comment]
Will look and test.

**Comment by lintool** [comment]
The invocation is now:

```
nohup sh target/appassembler/bin/IndexCollection -collection Gov2Collection \
 -input /scratch1/collections/gov2/gov2-corpus/ -generator JsoupGenerator \
 -index lucene-index.gov2.pos -threads 16 -positions -optimize > log.gov2.pos &
```

The idea is we could have different generators for different collection - a web one that uses Jsoup, a web one that uses a different parser, a generic newswire document one, etc.

**Comment by Peilin-Yang** [comment]
Tested and it works fine.
Only one concern: do you think it is better to put all the `Generator`s to another folder?

**Comment by lintool** [comment]
Done, created separate sub-package.
Closed.
